-- Create comments table
CREATE TABLE IF NOT EXISTS public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  author_name TEXT NOT NULL,
  author_email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- Select policy: Allow anyone to view comments
CREATE POLICY "Allow public read access on comments" 
ON public.comments FOR SELECT 
TO public 
USING (true);

-- Write policy: Allow authenticated users to add comments
CREATE POLICY "Allow write access on comments to authenticated" 
ON public.comments FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);
