-- 1. Create Notices Table (Announcements by Admin)
CREATE TABLE IF NOT EXISTS public.notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT DEFAULT 'Prof. Alkema',
  file_name TEXT,
  file_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Allow public read access on notices" 
ON public.notices FOR SELECT 
TO public 
USING (true);

-- Allow all access to authenticated admin users (we can set simple policy for testing)
CREATE POLICY "Allow write access to authenticated users on notices" 
ON public.notices FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);


-- 2. Create Free Board Posts Table (By Students)
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author_name TEXT NOT NULL,
  author_email TEXT NOT NULL,
  file_name_1 TEXT,
  file_url_1 TEXT,
  file_name_2 TEXT,
  file_url_2 TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Allow public read access on posts" 
ON public.posts FOR SELECT 
TO public 
USING (true);

-- Allow write access to authenticated users
CREATE POLICY "Allow insert/write access on posts to authenticated" 
ON public.posts FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);


-- 3. Create Gallery Photos Table (By Admin)
CREATE TABLE IF NOT EXISTS public.gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  likes INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone
CREATE POLICY "Allow public read access on gallery" 
ON public.gallery FOR SELECT 
TO public 
USING (true);

-- Allow write/update access to authenticated users (like admin uploads)
CREATE POLICY "Allow write access on gallery to authenticated" 
ON public.gallery FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);
